// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xiaomi_auth_only.proto
// NOTE (sleepmon, Этап B): pre-generated artifact, no Gradle protobuf plugin (see
// build.gradle.kts note - incompatible with AGP 9.x). Regenerate with:
//   protoc --java_out=lite:<out> xiaomi_auth_only.proto
// Adds the `Health` message (activityRequestFileIds/activitySyncAckFileIds) needed for
// Этап B (activity data fetch) on top of the Этап A auth-only schema.
// Protobuf Java Version: 3.25.3
package com.example.sleepmonitorsync.band.proto;

public final class XiaomiProto {
  private XiaomiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CommandOrBuilder extends
      com.google.protobuf.MessageLiteOrBuilder {
    boolean hasType();
    int getType();
    boolean hasSubtype();
    int getSubtype();
    boolean hasAuth();
    com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth getAuth();
    boolean hasHealth();
    com.example.sleepmonitorsync.band.proto.XiaomiProto.Health getHealth();
    boolean hasStatus();
    int getStatus();
  }
  public  static final class Command extends
      com.google.protobuf.GeneratedMessageLite<
          Command, Command.Builder> implements
      CommandOrBuilder {
    private Command() {
    }
    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    @java.lang.Override
    public int getType() {
      return type_;
    }
    private void setType(int value) {
      bitField0_ |= 0x00000001;
      type_ = value;
    }
    private void clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
    }

    public static final int SUBTYPE_FIELD_NUMBER = 2;
    private int subtype_;
    @java.lang.Override
    public boolean hasSubtype() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    @java.lang.Override
    public int getSubtype() {
      return subtype_;
    }
    private void setSubtype(int value) {
      bitField0_ |= 0x00000002;
      subtype_ = value;
    }
    private void clearSubtype() {
      bitField0_ = (bitField0_ & ~0x00000002);
      subtype_ = 0;
    }

    public static final int AUTH_FIELD_NUMBER = 3;
    private com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth auth_;
    @java.lang.Override
    public boolean hasAuth() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    @java.lang.Override
    public com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth getAuth() {
      return auth_ == null ? com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth.getDefaultInstance() : auth_;
    }
    private void setAuth(com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth value) {
      value.getClass();
  auth_ = value;
      bitField0_ |= 0x00000004;
      }
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeAuth(com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth value) {
      value.getClass();
  if (auth_ != null &&
          auth_ != com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth.getDefaultInstance()) {
        auth_ =
          com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth.newBuilder(auth_).mergeFrom(value).buildPartial();
      } else {
        auth_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    private void clearAuth() {  auth_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public static final int HEALTH_FIELD_NUMBER = 10;
    private com.example.sleepmonitorsync.band.proto.XiaomiProto.Health health_;
    @java.lang.Override
    public boolean hasHealth() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    @java.lang.Override
    public com.example.sleepmonitorsync.band.proto.XiaomiProto.Health getHealth() {
      return health_ == null ? com.example.sleepmonitorsync.band.proto.XiaomiProto.Health.getDefaultInstance() : health_;
    }
    private void setHealth(com.example.sleepmonitorsync.band.proto.XiaomiProto.Health value) {
      value.getClass();
  health_ = value;
      bitField0_ |= 0x00000008;
      }
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeHealth(com.example.sleepmonitorsync.band.proto.XiaomiProto.Health value) {
      value.getClass();
  if (health_ != null &&
          health_ != com.example.sleepmonitorsync.band.proto.XiaomiProto.Health.getDefaultInstance()) {
        health_ =
          com.example.sleepmonitorsync.band.proto.XiaomiProto.Health.newBuilder(health_).mergeFrom(value).buildPartial();
      } else {
        health_ = value;
      }
      bitField0_ |= 0x00000008;
    }
    private void clearHealth() {  health_ = null;
      bitField0_ = (bitField0_ & ~0x00000008);
    }

    public static final int STATUS_FIELD_NUMBER = 100;
    private int status_;
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    private void setStatus(int value) {
      bitField0_ |= 0x00000010;
      status_ = value;
    }
    private void clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000010);
      status_ = 0;
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.sleepmonitorsync.band.proto.XiaomiProto.Command prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.sleepmonitorsync.band.proto.XiaomiProto.Command, Builder> implements
        com.example.sleepmonitorsync.band.proto.XiaomiProto.CommandOrBuilder {
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public boolean hasType() {
        return instance.hasType();
      }
      @java.lang.Override
      public int getType() {
        return instance.getType();
      }
      public Builder setType(int value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      @java.lang.Override
      public boolean hasSubtype() {
        return instance.hasSubtype();
      }
      @java.lang.Override
      public int getSubtype() {
        return instance.getSubtype();
      }
      public Builder setSubtype(int value) {
        copyOnWrite();
        instance.setSubtype(value);
        return this;
      }
      public Builder clearSubtype() {
        copyOnWrite();
        instance.clearSubtype();
        return this;
      }

      @java.lang.Override
      public boolean hasAuth() {
        return instance.hasAuth();
      }
      @java.lang.Override
      public com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth getAuth() {
        return instance.getAuth();
      }
      public Builder setAuth(com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth value) {
        copyOnWrite();
        instance.setAuth(value);
        return this;
        }
      public Builder setAuth(
          com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth.Builder builderForValue) {
        copyOnWrite();
        instance.setAuth(builderForValue.build());
        return this;
      }
      public Builder mergeAuth(com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth value) {
        copyOnWrite();
        instance.mergeAuth(value);
        return this;
      }
      public Builder clearAuth() {  copyOnWrite();
        instance.clearAuth();
        return this;
      }

      @java.lang.Override
      public boolean hasHealth() {
        return instance.hasHealth();
      }
      @java.lang.Override
      public com.example.sleepmonitorsync.band.proto.XiaomiProto.Health getHealth() {
        return instance.getHealth();
      }
      public Builder setHealth(com.example.sleepmonitorsync.band.proto.XiaomiProto.Health value) {
        copyOnWrite();
        instance.setHealth(value);
        return this;
        }
      public Builder setHealth(
          com.example.sleepmonitorsync.band.proto.XiaomiProto.Health.Builder builderForValue) {
        copyOnWrite();
        instance.setHealth(builderForValue.build());
        return this;
      }
      public Builder mergeHealth(com.example.sleepmonitorsync.band.proto.XiaomiProto.Health value) {
        copyOnWrite();
        instance.mergeHealth(value);
        return this;
      }
      public Builder clearHealth() {  copyOnWrite();
        instance.clearHealth();
        return this;
      }

      @java.lang.Override
      public boolean hasStatus() {
        return instance.hasStatus();
      }
      @java.lang.Override
      public int getStatus() {
        return instance.getStatus();
      }
      public Builder setStatus(int value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.sleepmonitorsync.band.proto.XiaomiProto.Command();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "type_",
              "subtype_",
              "auth_",
              "health_",
              "status_",
            };
            java.lang.String info =
                "\u0001\u0005\u0000\u0001\u0001d\u0005\u0000\u0000\u0002\u0001\u150b\u0000\u0002\u100b" +
                "\u0001\u0003\u1409\u0002\n\u1009\u0003d\u100b\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.sleepmonitorsync.band.proto.XiaomiProto.Command> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.sleepmonitorsync.band.proto.XiaomiProto.Command.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.sleepmonitorsync.band.proto.XiaomiProto.Command>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }

    private static final com.example.sleepmonitorsync.band.proto.XiaomiProto.Command DEFAULT_INSTANCE;
    static {
      Command defaultInstance = new Command();
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Command.class, defaultInstance);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Command> PARSER;

    public static com.google.protobuf.Parser<Command> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AuthOrBuilder extends
      com.google.protobuf.MessageLiteOrBuilder {
    boolean hasUserId();
    java.lang.String getUserId();
    com.google.protobuf.ByteString
        getUserIdBytes();
    boolean hasStatus();
    int getStatus();
    boolean hasPhoneNonce();
    com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce getPhoneNonce();
    boolean hasWatchNonce();
    com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce getWatchNonce();
    boolean hasAuthStep3();
    com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 getAuthStep3();
    boolean hasAuthStep4();
    com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 getAuthStep4();
  }
  public  static final class Auth extends
      com.google.protobuf.GeneratedMessageLite<
          Auth, Auth.Builder> implements
      AuthOrBuilder {
    private Auth() {
      userId_ = "";
    }
    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 7;
    private java.lang.String userId_;
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    @java.lang.Override
    public java.lang.String getUserId() {
      return userId_;
    }
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    private void setUserId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      userId_ = value;
    }
    private void clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = getDefaultInstance().getUserId();
    }
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      userId_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    private void setStatus(int value) {
      bitField0_ |= 0x00000002;
      status_ = value;
    }
    private void clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = 0;
    }

    public static final int PHONENONCE_FIELD_NUMBER = 30;
    private com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce phoneNonce_;
    @java.lang.Override
    public boolean hasPhoneNonce() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    @java.lang.Override
    public com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce getPhoneNonce() {
      return phoneNonce_ == null ? com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce.getDefaultInstance() : phoneNonce_;
    }
    private void setPhoneNonce(com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce value) {
      value.getClass();
  phoneNonce_ = value;
      bitField0_ |= 0x00000004;
      }
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergePhoneNonce(com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce value) {
      value.getClass();
  if (phoneNonce_ != null &&
          phoneNonce_ != com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce.getDefaultInstance()) {
        phoneNonce_ =
          com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce.newBuilder(phoneNonce_).mergeFrom(value).buildPartial();
      } else {
        phoneNonce_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    private void clearPhoneNonce() {  phoneNonce_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public static final int WATCHNONCE_FIELD_NUMBER = 31;
    private com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce watchNonce_;
    @java.lang.Override
    public boolean hasWatchNonce() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    @java.lang.Override
    public com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce getWatchNonce() {
      return watchNonce_ == null ? com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce.getDefaultInstance() : watchNonce_;
    }
    private void setWatchNonce(com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce value) {
      value.getClass();
  watchNonce_ = value;
      bitField0_ |= 0x00000008;
      }
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeWatchNonce(com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce value) {
      value.getClass();
  if (watchNonce_ != null &&
          watchNonce_ != com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce.getDefaultInstance()) {
        watchNonce_ =
          com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce.newBuilder(watchNonce_).mergeFrom(value).buildPartial();
      } else {
        watchNonce_ = value;
      }
      bitField0_ |= 0x00000008;
    }
    private void clearWatchNonce() {  watchNonce_ = null;
      bitField0_ = (bitField0_ & ~0x00000008);
    }

    public static final int AUTHSTEP3_FIELD_NUMBER = 32;
    private com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 authStep3_;
    @java.lang.Override
    public boolean hasAuthStep3() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    @java.lang.Override
    public com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 getAuthStep3() {
      return authStep3_ == null ? com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3.getDefaultInstance() : authStep3_;
    }
    private void setAuthStep3(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 value) {
      value.getClass();
  authStep3_ = value;
      bitField0_ |= 0x00000010;
      }
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeAuthStep3(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 value) {
      value.getClass();
  if (authStep3_ != null &&
          authStep3_ != com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3.getDefaultInstance()) {
        authStep3_ =
          com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3.newBuilder(authStep3_).mergeFrom(value).buildPartial();
      } else {
        authStep3_ = value;
      }
      bitField0_ |= 0x00000010;
    }
    private void clearAuthStep3() {  authStep3_ = null;
      bitField0_ = (bitField0_ & ~0x00000010);
    }

    public static final int AUTHSTEP4_FIELD_NUMBER = 33;
    private com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 authStep4_;
    @java.lang.Override
    public boolean hasAuthStep4() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    @java.lang.Override
    public com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 getAuthStep4() {
      return authStep4_ == null ? com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4.getDefaultInstance() : authStep4_;
    }
    private void setAuthStep4(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 value) {
      value.getClass();
  authStep4_ = value;
      bitField0_ |= 0x00000020;
      }
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeAuthStep4(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 value) {
      value.getClass();
  if (authStep4_ != null &&
          authStep4_ != com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4.getDefaultInstance()) {
        authStep4_ =
          com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4.newBuilder(authStep4_).mergeFrom(value).buildPartial();
      } else {
        authStep4_ = value;
      }
      bitField0_ |= 0x00000020;
    }
    private void clearAuthStep4() {  authStep4_ = null;
      bitField0_ = (bitField0_ & ~0x00000020);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth, Builder> implements
        com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthOrBuilder {
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public boolean hasUserId() {
        return instance.hasUserId();
      }
      @java.lang.Override
      public java.lang.String getUserId() {
        return instance.getUserId();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      public Builder setUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      @java.lang.Override
      public boolean hasStatus() {
        return instance.hasStatus();
      }
      @java.lang.Override
      public int getStatus() {
        return instance.getStatus();
      }
      public Builder setStatus(int value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      @java.lang.Override
      public boolean hasPhoneNonce() {
        return instance.hasPhoneNonce();
      }
      @java.lang.Override
      public com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce getPhoneNonce() {
        return instance.getPhoneNonce();
      }
      public Builder setPhoneNonce(com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce value) {
        copyOnWrite();
        instance.setPhoneNonce(value);
        return this;
        }
      public Builder setPhoneNonce(
          com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce.Builder builderForValue) {
        copyOnWrite();
        instance.setPhoneNonce(builderForValue.build());
        return this;
      }
      public Builder mergePhoneNonce(com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce value) {
        copyOnWrite();
        instance.mergePhoneNonce(value);
        return this;
      }
      public Builder clearPhoneNonce() {  copyOnWrite();
        instance.clearPhoneNonce();
        return this;
      }

      @java.lang.Override
      public boolean hasWatchNonce() {
        return instance.hasWatchNonce();
      }
      @java.lang.Override
      public com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce getWatchNonce() {
        return instance.getWatchNonce();
      }
      public Builder setWatchNonce(com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce value) {
        copyOnWrite();
        instance.setWatchNonce(value);
        return this;
        }
      public Builder setWatchNonce(
          com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce.Builder builderForValue) {
        copyOnWrite();
        instance.setWatchNonce(builderForValue.build());
        return this;
      }
      public Builder mergeWatchNonce(com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce value) {
        copyOnWrite();
        instance.mergeWatchNonce(value);
        return this;
      }
      public Builder clearWatchNonce() {  copyOnWrite();
        instance.clearWatchNonce();
        return this;
      }

      @java.lang.Override
      public boolean hasAuthStep3() {
        return instance.hasAuthStep3();
      }
      @java.lang.Override
      public com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 getAuthStep3() {
        return instance.getAuthStep3();
      }
      public Builder setAuthStep3(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 value) {
        copyOnWrite();
        instance.setAuthStep3(value);
        return this;
        }
      public Builder setAuthStep3(
          com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3.Builder builderForValue) {
        copyOnWrite();
        instance.setAuthStep3(builderForValue.build());
        return this;
      }
      public Builder mergeAuthStep3(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 value) {
        copyOnWrite();
        instance.mergeAuthStep3(value);
        return this;
      }
      public Builder clearAuthStep3() {  copyOnWrite();
        instance.clearAuthStep3();
        return this;
      }

      @java.lang.Override
      public boolean hasAuthStep4() {
        return instance.hasAuthStep4();
      }
      @java.lang.Override
      public com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 getAuthStep4() {
        return instance.getAuthStep4();
      }
      public Builder setAuthStep4(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 value) {
        copyOnWrite();
        instance.setAuthStep4(value);
        return this;
        }
      public Builder setAuthStep4(
          com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4.Builder builderForValue) {
        copyOnWrite();
        instance.setAuthStep4(builderForValue.build());
        return this;
      }
      public Builder mergeAuthStep4(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 value) {
        copyOnWrite();
        instance.mergeAuthStep4(value);
        return this;
      }
      public Builder clearAuthStep4() {  copyOnWrite();
        instance.clearAuthStep4();
        return this;
      }
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "userId_",
              "status_",
              "phoneNonce_",
              "watchNonce_",
              "authStep3_",
              "authStep4_",
            };
            java.lang.String info =
                "\u0001\u0006\u0000\u0001\u0007!\u0006\u0000\u0000\u0004\u0007\u1008\u0000\b\u100b" +
                "\u0001\u001e\u1409\u0002\u001f\u1409\u0003 \u1409\u0004!\u1409\u0005";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }

    private static final com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth DEFAULT_INSTANCE;
    static {
      Auth defaultInstance = new Auth();
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Auth.class, defaultInstance);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.Auth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Auth> PARSER;

    public static com.google.protobuf.Parser<Auth> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PhoneNonceOrBuilder extends
      com.google.protobuf.MessageLiteOrBuilder {
    boolean hasNonce();
    com.google.protobuf.ByteString getNonce();
  }
  public  static final class PhoneNonce extends
      com.google.protobuf.GeneratedMessageLite<
          PhoneNonce, PhoneNonce.Builder> implements
      PhoneNonceOrBuilder {
    private PhoneNonce() {
      nonce_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int NONCE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString nonce_;
    @java.lang.Override
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }
    private void setNonce(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      nonce_ = value;
    }
    private void clearNonce() {
      bitField0_ = (bitField0_ & ~0x00000001);
      nonce_ = getDefaultInstance().getNonce();
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce, Builder> implements
        com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonceOrBuilder {
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public boolean hasNonce() {
        return instance.hasNonce();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString getNonce() {
        return instance.getNonce();
      }
      public Builder setNonce(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNonce(value);
        return this;
      }
      public Builder clearNonce() {
        copyOnWrite();
        instance.clearNonce();
        return this;
      }
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "nonce_",
            };
            java.lang.String info =
                "\u0001\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0001\u0001\u150a\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }

    private static final com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce DEFAULT_INSTANCE;
    static {
      PhoneNonce defaultInstance = new PhoneNonce();
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PhoneNonce.class, defaultInstance);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.PhoneNonce getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PhoneNonce> PARSER;

    public static com.google.protobuf.Parser<PhoneNonce> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface WatchNonceOrBuilder extends
      com.google.protobuf.MessageLiteOrBuilder {
    boolean hasNonce();
    com.google.protobuf.ByteString getNonce();
    boolean hasHmac();
    com.google.protobuf.ByteString getHmac();
  }
  public  static final class WatchNonce extends
      com.google.protobuf.GeneratedMessageLite<
          WatchNonce, WatchNonce.Builder> implements
      WatchNonceOrBuilder {
    private WatchNonce() {
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      hmac_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int NONCE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString nonce_;
    @java.lang.Override
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }
    private void setNonce(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      nonce_ = value;
    }
    private void clearNonce() {
      bitField0_ = (bitField0_ & ~0x00000001);
      nonce_ = getDefaultInstance().getNonce();
    }

    public static final int HMAC_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString hmac_;
    @java.lang.Override
    public boolean hasHmac() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    @java.lang.Override
    public com.google.protobuf.ByteString getHmac() {
      return hmac_;
    }
    private void setHmac(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      hmac_ = value;
    }
    private void clearHmac() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hmac_ = getDefaultInstance().getHmac();
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce, Builder> implements
        com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonceOrBuilder {
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public boolean hasNonce() {
        return instance.hasNonce();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString getNonce() {
        return instance.getNonce();
      }
      public Builder setNonce(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNonce(value);
        return this;
      }
      public Builder clearNonce() {
        copyOnWrite();
        instance.clearNonce();
        return this;
      }

      @java.lang.Override
      public boolean hasHmac() {
        return instance.hasHmac();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString getHmac() {
        return instance.getHmac();
      }
      public Builder setHmac(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHmac(value);
        return this;
      }
      public Builder clearHmac() {
        copyOnWrite();
        instance.clearHmac();
        return this;
      }
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "nonce_",
              "hmac_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u150a\u0000\u0002" +
                "\u150a\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }

    private static final com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce DEFAULT_INSTANCE;
    static {
      WatchNonce defaultInstance = new WatchNonce();
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WatchNonce.class, defaultInstance);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.WatchNonce getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WatchNonce> PARSER;

    public static com.google.protobuf.Parser<WatchNonce> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AuthStep3OrBuilder extends
      com.google.protobuf.MessageLiteOrBuilder {
    boolean hasEncryptedNonces();
    com.google.protobuf.ByteString getEncryptedNonces();
    boolean hasEncryptedDeviceInfo();
    com.google.protobuf.ByteString getEncryptedDeviceInfo();
  }
  public  static final class AuthStep3 extends
      com.google.protobuf.GeneratedMessageLite<
          AuthStep3, AuthStep3.Builder> implements
      AuthStep3OrBuilder {
    private AuthStep3() {
      encryptedNonces_ = com.google.protobuf.ByteString.EMPTY;
      encryptedDeviceInfo_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int ENCRYPTEDNONCES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encryptedNonces_;
    @java.lang.Override
    public boolean hasEncryptedNonces() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedNonces() {
      return encryptedNonces_;
    }
    private void setEncryptedNonces(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      encryptedNonces_ = value;
    }
    private void clearEncryptedNonces() {
      bitField0_ = (bitField0_ & ~0x00000001);
      encryptedNonces_ = getDefaultInstance().getEncryptedNonces();
    }

    public static final int ENCRYPTEDDEVICEINFO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString encryptedDeviceInfo_;
    @java.lang.Override
    public boolean hasEncryptedDeviceInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedDeviceInfo() {
      return encryptedDeviceInfo_;
    }
    private void setEncryptedDeviceInfo(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      encryptedDeviceInfo_ = value;
    }
    private void clearEncryptedDeviceInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      encryptedDeviceInfo_ = getDefaultInstance().getEncryptedDeviceInfo();
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3, Builder> implements
        com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3OrBuilder {
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public boolean hasEncryptedNonces() {
        return instance.hasEncryptedNonces();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString getEncryptedNonces() {
        return instance.getEncryptedNonces();
      }
      public Builder setEncryptedNonces(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEncryptedNonces(value);
        return this;
      }
      public Builder clearEncryptedNonces() {
        copyOnWrite();
        instance.clearEncryptedNonces();
        return this;
      }

      @java.lang.Override
      public boolean hasEncryptedDeviceInfo() {
        return instance.hasEncryptedDeviceInfo();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString getEncryptedDeviceInfo() {
        return instance.getEncryptedDeviceInfo();
      }
      public Builder setEncryptedDeviceInfo(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEncryptedDeviceInfo(value);
        return this;
      }
      public Builder clearEncryptedDeviceInfo() {
        copyOnWrite();
        instance.clearEncryptedDeviceInfo();
        return this;
      }
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "encryptedNonces_",
              "encryptedDeviceInfo_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u150a\u0000\u0002" +
                "\u150a\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }

    private static final com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 DEFAULT_INSTANCE;
    static {
      AuthStep3 defaultInstance = new AuthStep3();
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AuthStep3.class, defaultInstance);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep3 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AuthStep3> PARSER;

    public static com.google.protobuf.Parser<AuthStep3> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AuthStep4OrBuilder extends
      com.google.protobuf.MessageLiteOrBuilder {
    boolean hasUnknown1();
    int getUnknown1();
    boolean hasUnknown2();
    int getUnknown2();
  }
  public  static final class AuthStep4 extends
      com.google.protobuf.GeneratedMessageLite<
          AuthStep4, AuthStep4.Builder> implements
      AuthStep4OrBuilder {
    private AuthStep4() {
    }
    private int bitField0_;
    public static final int UNKNOWN1_FIELD_NUMBER = 1;
    private int unknown1_;
    @java.lang.Override
    public boolean hasUnknown1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    @java.lang.Override
    public int getUnknown1() {
      return unknown1_;
    }
    private void setUnknown1(int value) {
      bitField0_ |= 0x00000001;
      unknown1_ = value;
    }
    private void clearUnknown1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      unknown1_ = 0;
    }

    public static final int UNKNOWN2_FIELD_NUMBER = 2;
    private int unknown2_;
    @java.lang.Override
    public boolean hasUnknown2() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    @java.lang.Override
    public int getUnknown2() {
      return unknown2_;
    }
    private void setUnknown2(int value) {
      bitField0_ |= 0x00000002;
      unknown2_ = value;
    }
    private void clearUnknown2() {
      bitField0_ = (bitField0_ & ~0x00000002);
      unknown2_ = 0;
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4, Builder> implements
        com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4OrBuilder {
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public boolean hasUnknown1() {
        return instance.hasUnknown1();
      }
      @java.lang.Override
      public int getUnknown1() {
        return instance.getUnknown1();
      }
      public Builder setUnknown1(int value) {
        copyOnWrite();
        instance.setUnknown1(value);
        return this;
      }
      public Builder clearUnknown1() {
        copyOnWrite();
        instance.clearUnknown1();
        return this;
      }

      @java.lang.Override
      public boolean hasUnknown2() {
        return instance.hasUnknown2();
      }
      @java.lang.Override
      public int getUnknown2() {
        return instance.getUnknown2();
      }
      public Builder setUnknown2(int value) {
        copyOnWrite();
        instance.setUnknown2(value);
        return this;
      }
      public Builder clearUnknown2() {
        copyOnWrite();
        instance.clearUnknown2();
        return this;
      }
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "unknown1_",
              "unknown2_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0001\u0001\u150b\u0000\u0002" +
                "\u100b\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }

    private static final com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 DEFAULT_INSTANCE;
    static {
      AuthStep4 defaultInstance = new AuthStep4();
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AuthStep4.class, defaultInstance);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthStep4 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AuthStep4> PARSER;

    public static com.google.protobuf.Parser<AuthStep4> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AuthDeviceInfoOrBuilder extends
      com.google.protobuf.MessageLiteOrBuilder {
    boolean hasUnknown1();
    int getUnknown1();
    boolean hasPhoneApiLevel();
    float getPhoneApiLevel();
    boolean hasPhoneName();
    java.lang.String getPhoneName();
    com.google.protobuf.ByteString
        getPhoneNameBytes();
    boolean hasUnknown3();
    int getUnknown3();
    boolean hasRegion();
    java.lang.String getRegion();
    com.google.protobuf.ByteString
        getRegionBytes();
  }
  public  static final class AuthDeviceInfo extends
      com.google.protobuf.GeneratedMessageLite<
          AuthDeviceInfo, AuthDeviceInfo.Builder> implements
      AuthDeviceInfoOrBuilder {
    private AuthDeviceInfo() {
      phoneName_ = "";
      region_ = "";
    }
    private int bitField0_;
    public static final int UNKNOWN1_FIELD_NUMBER = 1;
    private int unknown1_;
    @java.lang.Override
    public boolean hasUnknown1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    @java.lang.Override
    public int getUnknown1() {
      return unknown1_;
    }
    private void setUnknown1(int value) {
      bitField0_ |= 0x00000001;
      unknown1_ = value;
    }
    private void clearUnknown1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      unknown1_ = 0;
    }

    public static final int PHONEAPILEVEL_FIELD_NUMBER = 2;
    private float phoneApiLevel_;
    @java.lang.Override
    public boolean hasPhoneApiLevel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    @java.lang.Override
    public float getPhoneApiLevel() {
      return phoneApiLevel_;
    }
    private void setPhoneApiLevel(float value) {
      bitField0_ |= 0x00000002;
      phoneApiLevel_ = value;
    }
    private void clearPhoneApiLevel() {
      bitField0_ = (bitField0_ & ~0x00000002);
      phoneApiLevel_ = 0F;
    }

    public static final int PHONENAME_FIELD_NUMBER = 3;
    private java.lang.String phoneName_;
    @java.lang.Override
    public boolean hasPhoneName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    @java.lang.Override
    public java.lang.String getPhoneName() {
      return phoneName_;
    }
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(phoneName_);
    }
    private void setPhoneName(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000004;
      phoneName_ = value;
    }
    private void clearPhoneName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      phoneName_ = getDefaultInstance().getPhoneName();
    }
    private void setPhoneNameBytes(
        com.google.protobuf.ByteString value) {
      phoneName_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static final int UNKNOWN3_FIELD_NUMBER = 4;
    private int unknown3_;
    @java.lang.Override
    public boolean hasUnknown3() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    @java.lang.Override
    public int getUnknown3() {
      return unknown3_;
    }
    private void setUnknown3(int value) {
      bitField0_ |= 0x00000008;
      unknown3_ = value;
    }
    private void clearUnknown3() {
      bitField0_ = (bitField0_ & ~0x00000008);
      unknown3_ = 0;
    }

    public static final int REGION_FIELD_NUMBER = 5;
    private java.lang.String region_;
    @java.lang.Override
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    @java.lang.Override
    public java.lang.String getRegion() {
      return region_;
    }
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(region_);
    }
    private void setRegion(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000010;
      region_ = value;
    }
    private void clearRegion() {
      bitField0_ = (bitField0_ & ~0x00000010);
      region_ = getDefaultInstance().getRegion();
    }
    private void setRegionBytes(
        com.google.protobuf.ByteString value) {
      region_ = value.toStringUtf8();
      bitField0_ |= 0x00000010;
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfo, Builder> implements
        com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfoOrBuilder {
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public boolean hasUnknown1() {
        return instance.hasUnknown1();
      }
      @java.lang.Override
      public int getUnknown1() {
        return instance.getUnknown1();
      }
      public Builder setUnknown1(int value) {
        copyOnWrite();
        instance.setUnknown1(value);
        return this;
      }
      public Builder clearUnknown1() {
        copyOnWrite();
        instance.clearUnknown1();
        return this;
      }

      @java.lang.Override
      public boolean hasPhoneApiLevel() {
        return instance.hasPhoneApiLevel();
      }
      @java.lang.Override
      public float getPhoneApiLevel() {
        return instance.getPhoneApiLevel();
      }
      public Builder setPhoneApiLevel(float value) {
        copyOnWrite();
        instance.setPhoneApiLevel(value);
        return this;
      }
      public Builder clearPhoneApiLevel() {
        copyOnWrite();
        instance.clearPhoneApiLevel();
        return this;
      }

      @java.lang.Override
      public boolean hasPhoneName() {
        return instance.hasPhoneName();
      }
      @java.lang.Override
      public java.lang.String getPhoneName() {
        return instance.getPhoneName();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPhoneNameBytes() {
        return instance.getPhoneNameBytes();
      }
      public Builder setPhoneName(
          java.lang.String value) {
        copyOnWrite();
        instance.setPhoneName(value);
        return this;
      }
      public Builder clearPhoneName() {
        copyOnWrite();
        instance.clearPhoneName();
        return this;
      }
      public Builder setPhoneNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPhoneNameBytes(value);
        return this;
      }

      @java.lang.Override
      public boolean hasUnknown3() {
        return instance.hasUnknown3();
      }
      @java.lang.Override
      public int getUnknown3() {
        return instance.getUnknown3();
      }
      public Builder setUnknown3(int value) {
        copyOnWrite();
        instance.setUnknown3(value);
        return this;
      }
      public Builder clearUnknown3() {
        copyOnWrite();
        instance.clearUnknown3();
        return this;
      }

      @java.lang.Override
      public boolean hasRegion() {
        return instance.hasRegion();
      }
      @java.lang.Override
      public java.lang.String getRegion() {
        return instance.getRegion();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRegionBytes() {
        return instance.getRegionBytes();
      }
      public Builder setRegion(
          java.lang.String value) {
        copyOnWrite();
        instance.setRegion(value);
        return this;
      }
      public Builder clearRegion() {
        copyOnWrite();
        instance.clearRegion();
        return this;
      }
      public Builder setRegionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRegionBytes(value);
        return this;
      }
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "unknown1_",
              "phoneApiLevel_",
              "phoneName_",
              "unknown3_",
              "region_",
            };
            java.lang.String info =
                "\u0001\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0005\u0001\u150b\u0000\u0002" +
                "\u1501\u0001\u0003\u1508\u0002\u0004\u150b\u0003\u0005\u1508\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfo> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfo>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }

    private static final com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfo DEFAULT_INSTANCE;
    static {
      AuthDeviceInfo defaultInstance = new AuthDeviceInfo();
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AuthDeviceInfo.class, defaultInstance);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.AuthDeviceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AuthDeviceInfo> PARSER;

    public static com.google.protobuf.Parser<AuthDeviceInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HealthOrBuilder extends
      com.google.protobuf.MessageLiteOrBuilder {
    boolean hasActivityRequestFileIds();
    com.google.protobuf.ByteString getActivityRequestFileIds();
    boolean hasActivitySyncAckFileIds();
    com.google.protobuf.ByteString getActivitySyncAckFileIds();
  }
  public  static final class Health extends
      com.google.protobuf.GeneratedMessageLite<
          Health, Health.Builder> implements
      HealthOrBuilder {
    private Health() {
      activityRequestFileIds_ = com.google.protobuf.ByteString.EMPTY;
      activitySyncAckFileIds_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int ACTIVITYREQUESTFILEIDS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString activityRequestFileIds_;
    @java.lang.Override
    public boolean hasActivityRequestFileIds() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    @java.lang.Override
    public com.google.protobuf.ByteString getActivityRequestFileIds() {
      return activityRequestFileIds_;
    }
    private void setActivityRequestFileIds(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
      activityRequestFileIds_ = value;
    }
    private void clearActivityRequestFileIds() {
      bitField0_ = (bitField0_ & ~0x00000001);
      activityRequestFileIds_ = getDefaultInstance().getActivityRequestFileIds();
    }

    public static final int ACTIVITYSYNCACKFILEIDS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString activitySyncAckFileIds_;
    @java.lang.Override
    public boolean hasActivitySyncAckFileIds() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    @java.lang.Override
    public com.google.protobuf.ByteString getActivitySyncAckFileIds() {
      return activitySyncAckFileIds_;
    }
    private void setActivitySyncAckFileIds(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000002;
      activitySyncAckFileIds_ = value;
    }
    private void clearActivitySyncAckFileIds() {
      bitField0_ = (bitField0_ & ~0x00000002);
      activitySyncAckFileIds_ = getDefaultInstance().getActivitySyncAckFileIds();
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.Health parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.sleepmonitorsync.band.proto.XiaomiProto.Health prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.sleepmonitorsync.band.proto.XiaomiProto.Health, Builder> implements
        com.example.sleepmonitorsync.band.proto.XiaomiProto.HealthOrBuilder {
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public boolean hasActivityRequestFileIds() {
        return instance.hasActivityRequestFileIds();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString getActivityRequestFileIds() {
        return instance.getActivityRequestFileIds();
      }
      public Builder setActivityRequestFileIds(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setActivityRequestFileIds(value);
        return this;
      }
      public Builder clearActivityRequestFileIds() {
        copyOnWrite();
        instance.clearActivityRequestFileIds();
        return this;
      }

      @java.lang.Override
      public boolean hasActivitySyncAckFileIds() {
        return instance.hasActivitySyncAckFileIds();
      }
      @java.lang.Override
      public com.google.protobuf.ByteString getActivitySyncAckFileIds() {
        return instance.getActivitySyncAckFileIds();
      }
      public Builder setActivitySyncAckFileIds(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setActivitySyncAckFileIds(value);
        return this;
      }
      public Builder clearActivitySyncAckFileIds() {
        copyOnWrite();
        instance.clearActivitySyncAckFileIds();
        return this;
      }
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.sleepmonitorsync.band.proto.XiaomiProto.Health();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "activityRequestFileIds_",
              "activitySyncAckFileIds_",
            };
            java.lang.String info =
                "\u0001\u0002\u0000\u0001\u0002\u0003\u0002\u0000\u0000\u0000\u0002\u100a\u0000\u0003" +
                "\u100a\u0001";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.sleepmonitorsync.band.proto.XiaomiProto.Health> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.sleepmonitorsync.band.proto.XiaomiProto.Health.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.sleepmonitorsync.band.proto.XiaomiProto.Health>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }

    private static final com.example.sleepmonitorsync.band.proto.XiaomiProto.Health DEFAULT_INSTANCE;
    static {
      Health defaultInstance = new Health();
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Health.class, defaultInstance);
    }

    public static com.example.sleepmonitorsync.band.proto.XiaomiProto.Health getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Health> PARSER;

    public static com.google.protobuf.Parser<Health> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
